GitHub Actions: Linux native job without Docker | Fix building 32-bit AssetImporter on Ubuntu 64

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,8 +23,8 @@ jobs:
           git fetch --deepen=1
           git log --raw --no-merges -1 |grep '^:' >/tmp/whatchanged
           echo ::set-output name=skip::$(grep -cqv 'website/' /tmp/whatchanged; echo $?)
-  linux:
-    name: 🐧
+  linux-old:
+    name: 🐧-old
     runs-on: ubuntu-latest
     needs: init
     if: needs.init.outputs.skip == '0'
@@ -32,8 +32,6 @@ jobs:
       fail-fast: false
       matrix:
         platform:
-          - linux-gcc
-          - linux-clang
           - mingw
           - rpi
           - arm
@@ -309,6 +307,7 @@ jobs:
     name: ⚡ Emscripten
     runs-on: ubuntu-latest
     needs: init
+    #if: false
 
     strategy:
       fail-fast: false
@@ -348,7 +347,7 @@ jobs:
         BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
         BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
       run: |
-        echo "Current dir: $PWD"
+        echo "Current dir: $PWD" # $GITHUB_WORKSPACE
         cd engine_repo
         rake ci_publish_web
       if: | # If not PR
@@ -356,10 +355,135 @@ jobs:
           (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
       continue-on-error: ${{ !startsWith(github.ref, 'refs/tags/') }}
 
+  Linux_Native:
+    runs-on: ubuntu-latest
+    needs: init
+    if: needs.init.outputs.skip == '0'
+
+    strategy:
+      fail-fast: false
+      matrix:
+        COMPILER:
+        - {
+            ID: gcc,
+            C: gcc,
+            CXX: g++,
+          }
+        - {
+            ID: clang,
+            C: clang,
+            CXX: clang++,
+          }
+        BITS:
+        - 64
+        - 32
+        LIB_TYPE:
+        - {
+            ID: shared,
+            VALUE: SHARED,
+          }
+        - {
+            ID: static,
+            VALUE: STATIC,
+          }
+        BUILD_TYPE:
+        - {
+            ID: rel,
+            VALUE: Release,
+          }
+        - {
+            ID: dbg,
+            VALUE: Debug,
+          }
+
+    name: 🐧-${{ matrix.COMPILER.ID }}-${{ matrix.BITS }}-${{ matrix.LIB_TYPE.ID }}-${{ matrix.BUILD_TYPE.ID }}
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+      with: { path: "engine_repo" }
+
+    - name: Install dependencies
+      run: |
+        if [ "${{ matrix.BITS }}" == "32" ]; then
+          sudo dpkg --add-architecture i386
+          sudo apt update
+          sudo apt install gcc-multilib g++-multilib libxext-dev:i386 libgl1-mesa-dev:i386
+        else
+          sudo apt install libgl1-mesa-dev
+        fi
+
+    - name: Cache
+      uses: actions/cache@v3
+      with:
+        path: engine_build
+        key: linux-${{ matrix.COMPILER.ID }}-${{ matrix.BITS }}-${{ matrix.LIB_TYPE.ID }}-${{ matrix.BUILD_TYPE.ID }}-${{ github.sha }}
+        restore-keys: linux-${{ matrix.COMPILER.ID }}-${{ matrix.BITS }}-${{ matrix.LIB_TYPE.ID }}-${{ matrix.BUILD_TYPE.ID }}
+
+    - name: Build
+      run: |
+        #set -x # Echo commands
+        echo "Current dir: $PWD"
+
+        if [ "${{ matrix.BITS }}" == "32" ]
+        then
+          BITS64=0
+        else
+          BITS64=1
+        fi
+
+        cmake engine_repo -B engine_build -G "Unix Makefiles" \
+          -D CMAKE_C_COMPILER=${{ matrix.COMPILER.C }} -D CMAKE_CXX_COMPILER=${{ matrix.COMPILER.CXX }} \
+          -D URHO3D_DATABASE_SQLITE=1 -D URHO3D_TESTING=1 -D CMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE.VALUE }} \
+          -D URHO3D_64BIT=$BITS64 -D URHO3D_LIB_TYPE=${{ matrix.LIB_TYPE.VALUE }}
+
+        cmake --build engine_build
+
+    - name: CTest
+      shell: bash {0} # Allow catching errors
+      run: |
+        xvfb-run ctest --test-dir engine_build
+        EXIT_CODE=$? # Exit code of the previous command
+
+        if (( $EXIT_CODE != 0 )) 
+        then
+          echo "$(cat ~/.local/share/urho3d/logs/HelloWorld.log)"
+          exit $EXIT_CODE
+        fi
+
+    - name: Test tools
+      run: $GITHUB_WORKSPACE/engine_repo/script/test_tools.sh $GITHUB_WORKSPACE/engine_repo $GITHUB_WORKSPACE/engine_build
+
+    - name: Test app
+      run: |
+        #cmake --install engine_build --prefix=$HOME/installed_engine # Not works
+        #URHO3D_HOME=$HOME/installed_engine # Not works
+        #URHO3D_HOME=$GITHUB_WORKSPACE/engine_build # Not works
+        sudo cmake --build engine_build --target install
+        cd engine_repo
+        rake new
+        cd ..
+
+        if [ "${{ matrix.BITS }}" == "32" ]
+        then
+          BITS64=0
+        else
+          BITS64=1
+        fi
+
+        cmake $HOME/projects/UrhoApp -B $HOME/projects/UrhoApp_build -G "Unix Makefiles" \
+          -D CMAKE_C_COMPILER=${{ matrix.COMPILER.C }} -D CMAKE_CXX_COMPILER=${{ matrix.COMPILER.CXX }} \
+          -D URHO3D_DATABASE_SQLITE=1 -D URHO3D_TESTING=1 -D CMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE.VALUE }} \
+          -D URHO3D_64BIT=$BITS64 -D URHO3D_LIB_TYPE=${{ matrix.LIB_TYPE.VALUE }}
+
+        cmake --build $HOME/projects/UrhoApp_build
+        xvfb-run ctest --test-dir $HOME/projects/UrhoApp_build
+
   Android:
     name: 🤖 Android
     runs-on: ubuntu-latest
     needs: init
+    #if: false
 
     steps:
     - name: Checkout
